### ISSUE TITLE
Small bugs

### ISSUE THREAD

**Issue by zojoker** [outsetini/Air-for-Steam#101]
1. In the classic version, in Russian there is a bug. When loading the game, in the field "start download" time is superimposed on the inscription.
![1](https://cloud.githubusercontent.com/assets/16863453/12536061/0ba9f600-c2aa-11e5-975a-fa644a7ade25.png)

2. After you install the new game, the picture is still dark, corrected after restarting steam.
![2](https://cloud.githubusercontent.com/assets/16863453/12536062/149da07c-c2aa-11e5-9268-742f9fabb044.png)

**Comment by outsetini** [comment]
For future reference, there is a separate repo for Air Classic: https://github.com/outsetini/Air-Classic

I patched up the first issue, though the second one is something I can't fix due to Steam itself. I won't be doing a full release just for this, but you can download the patched version directly from the repo (Download ZIP button on the top-right).
