### ISSUE TITLE
A dialog without shadow in edge

### ISSUE THREAD

**Issue by oncegithub** [outsetini/Air-for-Steam#103]
when you try to create a shortcut on desktop like this(right-click game name and choose 'properties',select 'general' and click 'create......',it will show you a dialog window with success info,
but it doesn't have shadow in edge so it can't be seen clearly,please add one(and others have shadow).
![2016-02-25_13-09-20_steam](https://cloud.githubusercontent.com/assets/17466949/13310499/695367de-dbc1-11e5-8490-e9a3027edbb0.png)
![2016-02-25_13-09-31_steam](https://cloud.githubusercontent.com/assets/17466949/13310500/6956cd70-dbc1-11e5-967d-dd3f4d03be06.png)

**Comment by outsetini** [comment]
I'm aware of this issue and since it's mostly only an edge case (having a small dialog over a portion of the background of the same color), I'd rather not make sweeping changes to the skin. The only thing I can really do is add a border around the dialogs, which would be universal. Sadly, as much as I'd wish it, I have no control over adding drop shadows.

**Comment by CorruptComputer** [comment]
Just add a 1px border that is the same as the bar that has close on it.

**Comment by outsetini** [comment]
@CorruptComputer Yeah, I considered that (and previous versions of Air have had it), but I really just don't like how constrictive it makes the skin feel. Except for this issue, it helps the other windows breathe easier imo.
