### ISSUE TITLE
Relocation of the friends context menu

### ISSUE THREAD

**Issue by HyperHamster** [Outsetini/Air-for-Steam#112]
The context options to change your friends status from online to offline and etc. is located in the hamburger menu of the Library window and not the Friends window. It should be located in the Friends window instead because that is what it affects. If you don't wish to move it you could at least provide a clone of it in the hamburger menu of the Friends window.

**Comment by Outsetini** [comment]
There's an annoying bug that occurs with the checkmarks if you move the status options into the friends menu, which is why I had them moved over. For some reason the checks don't update properly when you select a new status in the friends menu, and it was causing a lot of confusion for people when they would have multiple status appearing selected.

This solution, while a little annoying, proved to be a lot less troublesome in the confusion department in the long run.
