### ISSUE TITLE
SteamVR Button

### ISSUE THREAD

**Issue by KitF** [Outsetini/Air-for-Steam#116]
Could we get a SteamVR shortcut in the top right like the default skin has?

**Comment by Outsetini** [comment]
I'd rather not have an icon on the main client window, but I did attempt to move the option into the main menu. Since I don't have VR personally, I haven't been able to test whether or not this link in the menu works. Could I ask you to check it out and let me know?

**Comment by KovuTheHusky** [comment]
Personally I'd prefer a button on the top right since it's more of a toggle on/off than something that belongs in a menu. It functions similarly to a lever/switch.

The vanilla Steam skin's way of doing it is nice and I'd love to see a similar implementation. Although maybe greyed-out versus white just like the notifications icon is in Air.

**Comment by Outsetini** [comment]
Archiving discussion. The SteamVR shortcut in the main menu wasn't functional, but VR can be launched from the game library.
