### ISSUE TITLE
Chat Window Enhancements

### ISSUE THREAD

**Issue by Ionaru** [Outsetini/Air-for-Steam#118]
Hello,

After using Air for a little while I've began noticing a few missing things that I had gotten used to having with other skins.

I'd like an icon in the chat window that indicates if the person I'm chatting with is currently on mobile or using the Steam Web Chat

An indicator to show if a person is away or busy.

Another thing that would be really useful is to show what game the person is currently playing, without having to hover over their icon in the bottom-right corner of the chat window (which doesn't always work).

**Comment by Outsetini** [comment]
These are things I would love to implement in a well designed manner, but sadly, due to the way Steam has things coded, I'm offered little freedom. To include the few missing items, I would essentially have to keep the chat window as it is in the default skin, which I'm not really a big fan of. I understand that it is an inconvenience, but I'd rather keep the slimmer design. If it were up to me, I'd do a complete overhaul of the chat window. There are so many ways to include the info you are looking for in creative ways without negatively impacting design...
