### ISSUE TITLE
Dota 2 crashes while using AirForSteam overlay

### ISSUE THREAD

**Issue by Roofkiller** [Outsetini/Air-for-Steam#124]
DotA 2 crashes after opening the steam overlay.

**Comment by Outsetini** [comment]
Can you please verify that the crashing does not occur while using the default skin? Also, please try re-downloading the most up to date version of Air to see if that helps.

**Comment by Roofkiller** [comment]
I have tried the last release and the latest Update of this repository. I have used the steam Beta channel version. It only occurs while using Air For Steam, other skins or default are fine.

**Comment by Outsetini** [comment]
Are there any specific actions that cause the crash or is it just when the overlay is first opened? Does the overlay crash with other games? If not, I have a couple of troubleshooting things you could help me with to pin down the issue:

In the layout directory `\Steam\skins\Air-for-Steam\Resource\layout`, you should see these files:

![capture](https://cloud.githubusercontent.com/assets/8676168/17835008/da49085e-670d-11e6-9fe9-65c34f398501.PNG)

If you remove them from the folder and try running Dota (restart Steam first), does it still crash? If not, can you systematically remove the files one at a time and see when the crashing stops? If you get this far, it will be best to start with overlaydashboard, overlaytaskbar, and overlaydesktop as they are the most likely canidates.

**Comment by Roofkiller** [comment]
This just happens with Dota when I open the overlay the first time. Removing the overlaydashboard.layout file fixed it.

**Comment by Outsetini** [comment]
Awesome. So, essentially, we're going to need to pinpoint the line of code that's causing the crash. I usually go about this by cutting the problem in half sequentially until you only have one option left. In this case, if you could open the overlaydashboard.layout file in a text editor (save an unedited copy to your desktop first so you can restore it) and remove the `styles` section. After restarting Steam it still crashes, put the styles section back and try the same thing with the `layout` section.

Once you have the problem section nailed down, just get more granular until you can pinpoint the code block with the issue and then finally the line causing the issue. Sorry, it's a pain, but since Steam lacks any useful console or inspect functionality (or crash reports for skins) this is sometimes the only way.

If you're familiar with code, you can ignore my overly detailed description, but here's an image outlining the code blocks. Just make sure you remove entire blocks at a time (defined by the brackets) or it will break for entirely different reasons.

![capture](https://cloud.githubusercontent.com/assets/8676168/17838979/930e57d2-678f-11e6-8958-20c221434c83.PNG)

**Comment by Roofkiller** [comment]
Okay line 10 causes the crashes. If I remove this line it works fine.

**Comment by Outsetini** [comment]
Can you try replacing `image_tiled` with `image_scale` on that line?

**Comment by Roofkiller** [comment]
Its not crashing. :+1:

**Comment by Outsetini** [comment]
Awesome, the latest commit should have that patched up for ya and I'll have an update out soon. Thanks for the help troubleshooting!
