### ISSUE TITLE
Family page breaks on setting toggle

### ISSUE THREAD

**Issue by StaticRocket** [Outsetini/Air-for-Steam#175]
![image](https://user-images.githubusercontent.com/35777938/38452451-810381a0-3a12-11e8-8653-07b22a3f69f8.png)
You must click away from that tab and then return to fix it. This can be solved by moving the assets that are spawned by the toggling of "Authorize library sharing on this computer" to be below the static elements.

**Comment by Outsetini** [comment]
I think I'd rather leave this one as is - it's a tossup between the bug or page layout/organization. I definitely feel that having a clearer sense of layout should stay priority since most people won't run into this bug. Also, as a side note, welcome to Steam, heh... ;)
![capture](https://user-images.githubusercontent.com/8676168/39034368-f7d704ba-442a-11e8-8894-6a0c820a381b.JPG)
